server:
  port: 8766

spring:
  application:
    name: Consumer
  thymeleaf:
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/